### ISSUE TITLE
Could not find an app file behave_bdd.app

### ISSUE THREAD

**Issue by ya-netgrp** [anyalir/behave#1]
Environment: `elixir: 1.15.4-otp-26`

Currently when trying to compile project with `:behave_bdd` as a dependency it fails with

```
Unchecked dependencies for environment dev:
* behave_bdd (Hex package)
  could not find an app file at "_build/dev/lib/behave_bdd/ebin/behave_bdd.app". Another app file was found in the same directory "_build/dev/lib/behave_bdd/ebin/behave.app", try changing the dependency name to :behave
** (Mix) Can't continue due to errors on dependencies
```

Looks like it expects that app name is `:behave_bdd`.

**Comment by ya-netgrp** [comment]
Can be solved with adding dependency with 

`{:behave, "~> 0.1.1", hex: :behave_bdd}`

Need only to change [documentation](https://github.com/anyalir/behave/blob/34f72a5f3893c02e745e19a6e023146ac919081f/README.md?plain=1#L130).

**Comment by anyalir** [comment]
Updated readme, thank you!
