### ISSUE TITLE
Warning: variable "data" is unused in `act` block 

### ISSUE THREAD

**Issue by ya-netgrp** [anyalir/behave#2]
Currently if inside `act` block there is no references to injected `data` variable this leads to unused variable warning. 

However there can be a scenario when there is a single `given` block before `act` that is used for side effect and returns `:ignore` so there is nothing to fetch from `data` in `act` block. 
Or another scenario when you can have one or more act blocks that rely on external state, only input arguments or even don't need additional data at all.

Another way to get same warning is to define local `data` variable inside `act` block. As marco variable `data` is hygienic it will not conflict with local `data` variable but it will be recognized as unused as well. 

I am personally recommend to not inject macro variables by default or at all and use special functions to retrieve it if caller needs it.

**Comment by anyalir** [comment]
Largely duplicates #3, and should be fixed there. Thanks for the feedback, will implement as soon as I have access to my laptop and time. 

Ofc, PRs welcome :)
