### ISSUE TITLE
Access to previous `act` data from a next `act` block

### ISSUE THREAD

**Issue by ya-netgrp** [anyalir/behave#7]
Not a bug but just a question/discussion about possibility.

Currently `act` block can access only data stored by the `given` block. In its turn data stored by (the last in case of overwriting) `act` block can be accessed only in the `check` block.
But what about access from `act` block to the data stored by previous `act` blocks? Currently it is not possible however it is easy to imagine possible scenarios for such possibility. 

So wanted to ask if there are some conceptual limitations on this? If not probably it makes sense to add support for such access.

**Comment by anyalir** [comment]
Sure this can be done. There isn't any conceptual block here. Again, for now you'll have to do that on a fork because I'm busy healing and on several pain meds. I wouldn't want to work even if I had my laptop with me.

**Comment by ya-netgrp** [comment]
Sure. I don't expect you to work on these issues now. It's just a list of things to work on regardless of who will solve them.

**Comment by anyalir** [comment]
Implemented in 0.2.0 :)
